# Generated by Django 5.2.17 on 2026-08-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('snils', models.CharField(max_length=14, unique=True, verbose_name='СНИЛС')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('vk', models.URLField(blank=True, verbose_name='VK')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('enrollment_year', models.PositiveSmallIntegerField(verbose_name='Год поступления')),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год окончания')),
                ('study_status', models.CharField(choices=[('studying', 'Обучается'), ('expelled', 'Отчислен'), ('graduated', 'Выпустился'), ('academic_leave', 'Академический отпуск')], default='studying', max_length=20, verbose_name='Статус обучения')),
                ('expulsion_reason', models.TextField(blank=True, verbose_name='Причина отчисления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['full_name'],
            },
        ),
    ]
