# Generated by Django 5.2.17 on 2026-08-07 06:35

import apps.students.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=18, validators=[apps.students.validators.validate_phone], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='student',
            name='snils',
            field=models.CharField(max_length=14, unique=True, validators=[apps.students.validators.validate_snils], verbose_name='СНИЛС'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['full_name'], name='students_st_full_na_6ea9f7_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['snils'], name='students_st_snils_54dfa2_idx'),
        ),
    ]
