# Generated by Django 5.2.17 on 2026-08-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Код направления')),
                ('name', models.CharField(max_length=255, verbose_name='Название направления')),
                ('education_level', models.CharField(choices=[('bachelor', 'Бакалавриат'), ('specialist', 'Специалитет'), ('master', 'Магистратура'), ('postgraduate', 'Аспирантура')], max_length=20, verbose_name='Уровень образования')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
            options={
                'verbose_name': 'Образовательная программа',
                'verbose_name_plural': 'Образовательные программы',
                'ordering': ['code', 'name'],
                'constraints': [models.UniqueConstraint(fields=('code', 'education_level'), name='unique_program_code_and_level')],
            },
        ),
    ]
