# Generated by Django 5.2.17 on 2026-08-10 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_educationalprogram'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationalProgram',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
