# Generated by Django 5.2.17 on 2026-08-12 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
        ('students', '0004_delete_educationalprogram_delete_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Причина')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Причина изменения обучения',
                'verbose_name_plural': 'Причины изменения обучения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EducationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_year', models.PositiveSmallIntegerField(verbose_name='Год обучения')),
                ('course', models.PositiveSmallIntegerField(verbose_name='Курс')),
                ('semester', models.PositiveSmallIntegerField(verbose_name='Семестр')),
                ('study_group', models.CharField(max_length=50, verbose_name='Учебная группа')),
                ('study_form', models.CharField(choices=[('full_time', 'Очная'), ('part_time', 'Заочная'), ('part_time_full', 'Очно-заочная')], max_length=20, verbose_name='Форма обучения')),
                ('funding_type', models.CharField(choices=[('budget', 'Бюджет'), ('contract', 'Контракт')], max_length=20, verbose_name='Тип финансирования')),
                ('status', models.CharField(choices=[('studying', 'Обучается'), ('academic_leave', 'Академический отпуск'), ('expelled', 'Отчислен'), ('graduated', 'Выпустился')], max_length=20, verbose_name='Статус обучения')),
                ('start_date', models.DateField(verbose_name='Начало обучения')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Конец обучения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_reasons', models.ManyToManyField(blank=True, related_name='education_history', to='students.changereason', verbose_name='Причины изменения')),
                ('educational_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='education_history', to='directories.educationalprogram', verbose_name='Образовательная программа')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='education_history', to='directories.faculty', verbose_name='Факультет')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_history', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'История обучения',
                'verbose_name_plural': 'История обучения',
                'ordering': ['student', 'start_date', 'course', 'semester'],
                'indexes': [models.Index(fields=['student', 'start_date'], name='students_ed_student_3adca7_idx'), models.Index(fields=['faculty', 'start_date'], name='students_ed_faculty_d0948e_idx'), models.Index(fields=['educational_program', 'start_date'], name='students_ed_educati_806283_idx'), models.Index(fields=['status'], name='students_ed_status_2aaf7a_idx'), models.Index(fields=['funding_type'], name='students_ed_funding_a8ead2_idx')],
            },
        ),
    ]
