# Generated by Django 5.2.17 on 2026-08-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
        ('students', '0006_rename_enrollment_year_to_academic_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationhistory',
            options={'ordering': ['student', 'academic_year', 'course', 'semester'], 'verbose_name': 'История обучения', 'verbose_name_plural': 'История обучения'},
        ),
        migrations.AlterField(
            model_name='educationhistory',
            name='academic_year',
            field=models.CharField(max_length=9, verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='educationhistory',
            name='status',
            field=models.CharField(choices=[('studying', 'Обучается'), ('transferred', 'Перевелся'), ('academic_leave', 'Академический отпуск'), ('expelled', 'Отчислен'), ('graduated', 'Выпустился')], max_length=20, verbose_name='Статус обучения'),
        ),
        migrations.AddConstraint(
            model_name='educationhistory',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year', 'course', 'semester'), name='unique_student_academic_period'),
        ),
    ]
