# Generated by Django 5.2.17 on 2026-08-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_educationhistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='educationhistory',
            name='unique_student_academic_period',
        ),
    ]
