# Generated by Django 5.2.17 on 2026-08-15 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_educationhistory_unique_student_academic_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationhistory',
            name='expulsion_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expulsion_history', to='students.changereason', verbose_name='Причина отчисления'),
        ),
    ]
