# Generated by Django 5.2.17 on 2026-08-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_educationhistory_expulsion_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationhistory',
            name='expulsion_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина отчисления'),
        ),
    ]
