# Generated by Django 5.2.17 on 2026-08-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_educationhistory_expulsion_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='study_status',
            field=models.CharField(choices=[('studying', 'Обучается'), ('transferred', 'Перевелся'), ('academic_leave', 'Академический отпуск'), ('expelled', 'Отчислен'), ('graduated', 'Выпустился')], default='studying', max_length=20, verbose_name='Статус обучения'),
        ),
    ]
