# Generated by Django 5.2.17 on 2026-08-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_study_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrollment_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='expulsion_reason',
        ),
        migrations.RemoveField(
            model_name='student',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='study_status',
        ),
    ]
