# Generated by Django 5.2.17 on 2026-09-01 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_contactperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255, verbose_name='Организация')),
                ('supervisor', models.CharField(max_length=255, verbose_name='Руководитель')),
                ('practice_type', models.CharField(choices=[('educational', 'Учебная'), ('industrial', 'Производственная'), ('research', 'Научно-исследовательская'), ('pregraduate', 'Преддипломная')], max_length=20, verbose_name='Вид практики')),
                ('semester', models.PositiveSmallIntegerField(verbose_name='Семестр')),
                ('referral_source', models.CharField(choices=[('university', 'Университет'), ('student', 'Сам студент'), ('organization', 'Организация'), ('career_center', 'Центр карьеры'), ('other', 'Другое')], max_length=30, verbose_name='Кто направил')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачивается')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practices', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Практика',
                'verbose_name_plural': 'Практики',
                'ordering': ['-semester', 'organization'],
                'indexes': [models.Index(fields=['student'], name='students_pr_student_93199c_idx'), models.Index(fields=['organization'], name='students_pr_organiz_10db21_idx'), models.Index(fields=['semester'], name='students_pr_semeste_3196cd_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'practice_type', 'semester'), name='unique_student_practice_type_semester')],
            },
        ),
    ]
