# Generated by Django 5.2.17 on 2026-09-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_practice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practice',
            options={'ordering': ['semester', 'organization'], 'verbose_name': 'Практика', 'verbose_name_plural': 'Практики'},
        ),
    ]
