# Generated by Django 5.2.17 on 2026-09-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_practice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
