# Generated by Django 5.2.17 on 2026-09-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_contactperson_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationhistory',
            name='planned_graduation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Планируемая дата выпуска'),
        ),
    ]
