# Generated by Django 5.2.17 on 2026-09-07 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_educationhistory_planned_graduation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_education_type', models.CharField(choices=[('mass_school', 'Массовая школа'), ('special_school', 'Специальная (коррекционная) школа'), ('home_school', 'Школа (домашнее обучение)'), ('college_general', 'Колледж, техникум (обучение в общей группе)'), ('college_special', 'Колледж, техникум (обучение в отдельной группе, индивидуальное обучение)'), ('other', 'Другое')], max_length=30, verbose_name='Предыдущее образование')),
                ('previous_education_other', models.CharField(blank=True, max_length=255, verbose_name='Другое (предыдущее образование)')),
                ('accommodation_type', models.CharField(choices=[('parents', 'С родителями, родственниками'), ('dormitory', 'В общежитии вуза'), ('rent', 'Снимать жилье'), ('own', 'В собственном жилье'), ('other', 'Другое')], max_length=20, verbose_name='Место проживания в период обучения')),
                ('accommodation_other', models.CharField(blank=True, max_length=255, verbose_name='Другое (место проживания)')),
                ('decision_time', models.CharField(choices=[('childhood', 'Много лет назад, мечта с детства'), ('senior_classes', 'При обучении в старших классах, при выборе профиля'), ('graduation_class', 'При обучении в выпускном классе (на последнем курсе)'), ('admission_campaign', 'Когда подавал документы в университет, во время приемной кампании'), ('other', 'Другое')], max_length=30, verbose_name='Когда принято решение о поступлении')),
                ('decision_time_other', models.CharField(blank=True, max_length=255, verbose_name='Другое (время принятия решения)')),
                ('choice_arguments', models.JSONField(default=list, verbose_name='Аргументы выбора образовательной программы')),
                ('choice_arguments_other', models.CharField(blank=True, max_length=500, verbose_name='Другое (аргумент выбора)')),
                ('art_types', models.TextField(blank=True, verbose_name='Виды искусства')),
                ('art_way', models.CharField(blank=True, choices=[('school_studio', 'Школа, студия и пр.'), ('self', 'Самостоятельно')], max_length=20, verbose_name='Как занимались искусством')),
                ('art_period', models.CharField(blank=True, choices=[('school_college', 'Во время учебы в школе (колледже)'), ('current', 'Продолжаю заниматься в настоящее время')], max_length=20, verbose_name='Когда занимались искусством')),
                ('art_achievements', models.TextField(blank=True, verbose_name='Достижения в искусстве')),
                ('creativity_types', models.TextField(blank=True, verbose_name='Виды творчества')),
                ('creativity_way', models.CharField(blank=True, choices=[('school_studio', 'Школа, студия и пр.'), ('self', 'Самостоятельно')], max_length=20, verbose_name='Как занимались творчеством')),
                ('creativity_period', models.CharField(blank=True, choices=[('school_college', 'Во время учебы в школе (колледже)'), ('current', 'Продолжаю заниматься в настоящее время')], max_length=20, verbose_name='Когда занимались творчеством')),
                ('creativity_achievements', models.TextField(blank=True, verbose_name='Достижения в творчестве')),
                ('sport_types', models.TextField(blank=True, verbose_name='Виды спорта')),
                ('sport_period', models.CharField(blank=True, choices=[('school_college', 'Во время учебы в школе (колледже)'), ('current', 'Продолжаю заниматься в настоящее время')], max_length=20, verbose_name='Когда занимались спортом')),
                ('sport_achievements', models.TextField(blank=True, verbose_name='Достижения в спорте')),
                ('social_activity_types', models.TextField(blank=True, verbose_name='Виды общественной деятельности')),
                ('social_activity_period', models.CharField(blank=True, choices=[('school_college', 'Во время учебы в школе (колледже)'), ('current', 'Продолжаю заниматься в настоящее время')], max_length=20, verbose_name='Когда занимались общественной деятельностью')),
                ('abilimpics', models.TextField(blank=True, verbose_name='Участие в чемпионатах «Абилимпикс»')),
                ('additional_information', models.TextField(blank=True, verbose_name='Дополнительные сведения')),
                ('preferred_contact_methods', models.JSONField(default=list, verbose_name='Предпочтительные способы связи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Анкета студента',
                'verbose_name_plural': 'Анкеты студентов',
            },
        ),
    ]
